import "./globals.css";
import { Poppins, Plus_Jakarta_Sans } from "next/font/google";
import Navbar from "@/src/components/Navbar";
import { ReactNode } from "react";
import Footer from "@/src/components/Footer";
import Script from "next/script"; // 👈 IMPORTANT

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-jakarta",
});

export const metadata = {
  title: "SoupX",
  description: "Generated by Next.js",
  icons: {
    icon: "/image 114.png",
  },
  metadataBase: new URL("https://www.soupx.health"),
  verification: {
    google: "8cX-856ZJnYs_zgp0fbqSVp3jQmb8K9_fKfFgs1vCS0",
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-6P83T9VR26"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-6P83T9VR26');
          `}
        </Script>
      </head>

      <body className={`${poppins.variable} ${jakarta.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
